### PR TITLE
(#10) - Rename namespaces and projects from Freshli.Cli and Freshli.Cli.Test …

### PR DESCRIPTION
**Pull request by mfcorgi**
…to Corgibytes.Freshli.Cli and Corgibytes.Freshli.Cli.Test

### CODE REVIEW

**Comment by mfcorgi** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by mairadanielaferrari** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by mairadanielaferrari** [comment]
recheck

**Review by mrbiggred — APPROVED** [review]
I don't see any issues.  Thanks for renaming all the files.

**Pull request merged**
