### PR TITLE
Git Clone Command (take 2)

### LINKED ISSUE #51: Add `git clone` command

### PR DESCRIPTION
**Pull request by CodeMouse92**
Resolves #51

### CODE REVIEW

**Comment by mscottford** [comment]
Before you started this effort up again, I was taking a peek at it yesterday. I didn't get very far, so there's really not much to share. I _do_ have the start at a Cucumber/Aruba feature file. I also did some research into whether or not the Ruby version of Cucumber supports the [Markdown syntax for feature files](https://github.com/cucumber/common/blob/main/gherkin/MARKDOWN_WITH_GHERKIN.md#markdown-with-gherkin). It does not. ☹️ 

What's the best way for me to share the draft feature file with you, @CodeMouse92?

**Comment by mscottford** [comment]
Also, after skimming through the implementation here, I think that using the library that I [referenced in a comment](https://github.com/corgibytes/freshli-cli/issues/51#issuecomment-1146176968) on #51 would be a big help.

**Comment by CodeMouse92** [comment]
> What's the best way for me to share the draft feature file with you, @CodeMouse92?

If it's just the one file, this sounds like a job for a Gist. If it's more complicated, a PR against this branch would be welcome.

**Comment by mscottford** [comment]
> > What's the best way for me to share the draft feature file with you, @CodeMouse92?
> 
> If it's just the one file, this sounds like a job for a Gist. If it's more complicated, a PR against this branch would be welcome.

Here you go. It's just a very rough start: https://gist.github.com/mscottford/c1ce426653b5a7ae257e18a1a9b8072a

**Comment by CodeMouse92** [comment]
I've been out sick for over a week. I'd intended to add the Cucumber feature test, but other than that, you can review at will.

**Comment by CodeMouse92** [comment]
Because using CliWrap will require a major refactor to incorporate asynchrony throughout, let's address that in a later commit.

**Comment by edwinkortman** [comment]
We pair reviewed this (@donabp, @CodeMouse92 and myself).

**Pull request merged**
